app/controllers/recipes_controller.py
# app/controllers/recipes_controller.py
import json
import re
import urllib.parse
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify
from flask_login import login_required, current_user
from app.models import Recipe, IngredientsSection, Ingredients, IngredientsMaster, InstructionSection, InstructionStep
from app import db
from app.data.links import links
from app.utils.fetch_recipe_data import fetch_recipe_data
from app.utils.process_recipe import process_recipe_content, processed_recipe_to_markdown


recipes_bp = Blueprint('recipes', __name__)

@recipes_bp.route('/')
@login_required
def recipes_list():
    recipes = Recipe.query.filter_by(created_by=current_user.id).all()
    return render_template('recipes.html', title='Recipes List', recipes=recipes, links=links)

@recipes_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create_recipe():
    if request.method == 'POST':
        # Create the main recipe object
        new_recipe = Recipe(
            # id=request.form['name'],
            name=request.form['name'],
            # recipe_image=request.form['image'],
            description=request.form['description'],
            keywords=request.form['keywords'],
            # author=request.form['author'],
            c_notes=request.form['notes'],
            prep_time=request.form['prep_time'], # TODO: Need to convert to ISO 8601 duration
            cook_time=request.form['cook_time'],
            # total_time= prep_time + cook_time, TODO: Need to calculate and convert to ISO 8601 duration
            recipe_yield=request.form['recipe_yield'],
            # recipe_cuisine=request.form['recipe_cuisine'], # TODO: Need to convert to recipe_cuisine and convert to JSON array
            # suitable_for_diet=request.form['suitable_for_diet'], # TODO: Need to convert to JSON array. This should be a multi-select.
            source=request.form['source'],
            recipe_ingredients_raw=request.form['ingredients'],
            recipe_instructions_raw=request.form['instructions'], 
            # nutrition=request.form['nutrition'], TODO: Need to create input and convert to JSON object.
            created_by=current_user.id
        )
        db.session.add(new_recipe)
        db.session.flush()  # Get the ID of the newly created recipe

        # Process each ingredient section
        section_index = 0
        while f'section_name_{section_index}' in request.form:
            section_name = request.form[f'section_name_{section_index}']
            new_section = IngredientsSection(
                recipe_id=new_recipe.id,
                name=section_name,
                c_order=section_index + 1,
                created_by=current_user.id
            )
            db.session.add(new_section)
            db.session.flush()

            # Process each ingredient in the section
            ingredient_index = 0
            while f'ingredient_name_{section_index}_{ingredient_index}' in request.form:
                ingredient_name = request.form[f'ingredient_name_{section_index}_{ingredient_index}']
                quantity = request.form[f'ingredient_quantity_{section_index}_{ingredient_index}']
                unit = request.form[f'ingredient_unit_{section_index}_{ingredient_index}']

                new_ingredient = Ingredients(
                    section_id=new_section.id,
                    name=ingredient_name,
                    quantity=quantity,
                    unit=unit,
                    created_by=current_user.id
                )
                db.session.add(new_ingredient)
                # ingredient_index += 1

            # section_index += 1

        db.session.commit()
        return redirect(url_for('recipes.recipes_list'))

    return render_template('recipe_create.html', title='Create a Recipe', recipe_data={})

@recipes_bp.route('/fetch', methods=['POST'])
@login_required
def fetch_recipe():
    url = request.form.get('url')
    data = fetch_recipe_data(url)
    if data:
        return render_template('recipe_create.html', title='Create Recipe', recipe_data=data)
    else:
        return render_template('recipe_create.html', title='Create Recipe', error="No structured data found.")

@recipes_bp.route('/process-recipe', methods=['POST'])
# @login_required()
def process_recipe():
    processed_recipe_data = {}
    
    # Extract the recipe content from the request
    processed_recipe_data['name'] = request.form.get('name')
    processed_recipe_data['description'] = request.form.get('description')
    processed_recipe_data['recipe_cuisine'] = request.form.get('recipe_cuisine')
    processed_recipe_data['keywords'] = request.form.get('keywords')
    processed_recipe_data['recipe_yield'] = request.form.get('recipe_yield')
    processed_recipe_data['prep_time'] = request.form.get('prep_time')
    processed_recipe_data['cook_time'] = request.form.get('cook_time')
    processed_recipe_data['notes'] = request.form.get('notes')
    processed_recipe_data['source'] = request.form.get('source')

    ingredients = request.form.get('ingredients')
    instructions = request.form.get('instructions')

    # print(recipe_name)
    # print(recipe_description)
                                    
    # # Assuming you have a function `process_recipe_content` that processes the recipe data
    schema_file_path = './app/data/schema/ingredients_instructions_schema_v1.json'
    processed_recipe = process_recipe_content(processed_recipe_data['name'], ingredients, instructions, schema_file_path)
    processed_recipe_data['recipeIngredients'], processed_recipe_data['recipeInstructions'] = processed_recipe_to_markdown(processed_recipe)

    # # Return the processed recipe as JSON
    return render_template('recipe_create.html', title='Create Recipe', recipe_data=processed_recipe_data)

@recipes_bp.route('/<int:recipe_id>')
@login_required
def recipe_detail(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    return render_template('recipe_detail.html', title=f'Recipe: {recipe.name}', recipe=recipe)

@recipes_bp.route('/<int:recipe_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if request.method == 'POST':
        # handle form submission
        recipe.name = request.form['name']
        recipe.servings = request.form['servings']
        recipe.prep_time = request.form['prep_time']
        recipe.cook_time = request.form['cook_time']
        recipe.ingredients = request.form['ingredients']
        recipe.method = request.form['method']
        db.session.commit()
        return redirect(url_for('recipes.recipe_detail', recipe_id=recipe.id))
    return render_template('recipe_edit.html', title=f'Edit Recipe: {recipe.name}', recipe=recipe)

@recipes_bp.route('/<int:recipe_id>/delete', methods=['POST'])
@login_required
def delete_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    db.session.delete(recipe)
    db.session.commit()
    return redirect(url_for('recipes.recipes_list'))

from flask import render_template, request, jsonify

@recipes_bp.route('/add_section', methods=['POST'])
@login_required
def add_section():
    section_index = request.form.get('section_index', 0, type=int)
    return render_template('partials/_ingredient_section.html', section_index=section_index)

@recipes_bp.route('/add_ingredient', methods=['POST'])
@login_required
def add_ingredient():
    section_index = request.form.get('section_index', 0, type=int)
    ingredient_index = request.form.get('ingredient_index', 0, type=int)
    return render_template('partials/_ingredient.html', section_index=section_index, ingredient_index=ingredient_index)

app/controllers/user_controller.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_user, logout_user, login_required
from app.models import User
from app import db, bcrypt

user_bp = Blueprint('user', __name__)

@user_bp.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        hashed_password = bcrypt.generate_password_hash(request.form['password']).decode('utf-8')
        user = User(username=request.form['username'], password=hashed_password)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('main.index'))
    return render_template('sign-up-form.html', title='Sign Up')

@user_bp.route('/log-in', methods=['GET', 'POST'])
def log_in():
    if request.method == 'POST':
        user = User.query.filter_by(username=request.form['username']).first()
        if user and bcrypt.check_password_hash(user.password, request.form['password']):
            login_user(user)
            return redirect(url_for('recipes.recipes_list'))
    return render_template('log-in.html', title='Log In')

@user_bp.route('/log-out')
@login_required
def log_out():
    logout_user()
    return redirect(url_for('main.index'))

app/templates/index.html
<!-- templates/index.html -->

{% extends 'layout.html' %} {% block content %}

<div class="container-fluid h-100">
  <div class="row h-100">
    {% include 'partials/home_side_panel.html' %}
    <div
      class="col-md-9 d-flex flex-column align-items-center justify-content-center"
    >
      {% if current_user.is_authenticated %}
      <div class="text-center mb-4">
        <h2>Welcome back</h2>
        <h2>{{ current_user.username }}</h2>
      </div>
      <div class="text-center">
        <button
          onclick="window.location.href='{{ url_for('recipes.recipes_list')}}'"
          class="btn btn-primary mb-2"
        >
          Go to App
        </button>
        <button
          onclick="window.location.href='{{ url_for('user.log_out') }}'"
          class="btn btn-primary"
        >
          Log out
        </button>
      </div>
      {% else %}
      <div class="w-50">
        <form
          action="{{ url_for('user.log_in') }}"
          method="POST"
          class="needs-validation"
          novalidate
        >
          <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input
              name="username"
              type="text"
              class="form-control"
              id="username"
              placeholder="username"
              required
            />
            <div class="invalid-feedback">Please enter your username.</div>
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input
              name="password"
              type="password"
              class="form-control"
              id="password"
              placeholder="password"
              required
            />
            <div class="invalid-feedback">Please enter your password.</div>
          </div>
          <button type="submit" class="btn btn-primary w-100">Log In</button>
        </form>
        <button
          onclick="window.location.href='{{ url_for('user.sign_up') }}'"
          class="btn btn-secondary w-100 mt-3"
        >
          Sign up
        </button>
      </div>
      {% endif %}
    </div>
  </div>
</div>

<script>
  // Bootstrap validation script
  (function () {
    "use strict";
    var forms = document.querySelectorAll(".needs-validation");
    Array.prototype.slice.call(forms).forEach(function (form) {
      form.addEventListener(
        "submit",
        function (event) {
          if (!form.checkValidity()) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add("was-validated");
        },
        false
      );
    });
  })();
</script>

{% endblock %}

app/templates/layout.html
<!-- templates/layout.html -->

<!DOCTYPE html>
<html lang="">
  <head>
    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="/static/css/styles.css" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    <script src="/static/js/htmx.js"></script>
    <title>Savor Recipes</title>
  </head>
  <body>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

app/templates/recipe_create.html
<!-- app/templates/recipe_create.html -->

{% extends 'layout.html' %} {% block content %} {% include
'partials/nav_bar.html' with context %}

<div class="container mt-5 pt-4">
  <h1>{{ title }}</h1>
  <form id="fetch-recipe-form" action="/recipes/fetch" method="POST">
    <div class="form-group">
      <label for="url">Recipe URL:</label>
      <input type="url" class="form-control" id="url" name="url" required />
    </div>
    <button type="submit" class="btn btn-primary">Fetch Recipe Data</button>
  </form>

  <form
    id="create-recipe-form"
    action="/recipes/create"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-group">
      <label for="name">Name:</label>
      <input
        type="text"
        class="form-control"
        id="name"
        name="name"
        value="{{ recipe_data.name }}"
        required
      />
    </div>
    <div class="form-group">
      <label for="description">Description:</label>
      <textarea
        class="form-control"
        id="description"
        name="description"
        rows="3"
      >
{{ recipe_data.description }}</textarea
      >
    </div>
    <div class="form-group">
      <label for="recipe_cuisine">Recipe Cuisine:</label>
      <input
        type="text"
        class="form-control"
        id="recipe_cuisine"
        name="recipe_cuisine"
        value="{{ recipe_data.recipe_cuisine }}"
      />
    </div>
    <div class="form-group">
      <label for="keywords">Keywords:</label>
      <input
        type="text"
        class="form-control"
        id="keywords"
        name="keywords"
        value="{{ recipe_data.keywords }}"
      />
    </div>
    <div class="form-group">
      <label for="recipe_yield">Servings:</label>
      <input
        type="number"
        class="form-control"
        id="recipe_yield"
        name="recipe_yield"
        value="{{ recipe_data.recipe_yield }}"
      />
    </div>
    <div class="form-group">
      <label for="prep_time">Prep Time (minutes):</label>
      <input
        type="number"
        class="form-control"
        id="prep_time"
        name="prep_time"
        value="{{ recipe_data.prep_time }}"
      />
    </div>
    <div class="form-group">
      <label for="cook_time">Cook Time (minutes):</label>
      <input
        type="number"
        class="form-control"
        id="cook_time"
        name="cook_time"
        value="{{ recipe_data.cook_time }}"
      />
    </div>

    <div class="form-group">
      <label for="ingredients">Ingredients:</label>
      <textarea
        class="form-control"
        id="ingredients"
        name="ingredients"
        rows="5"
      >
{{ recipe_data.recipeIngredients }}</textarea
      >
    </div>

    <div class="form-group">
      <label for="instructions">Method:</label>
      <textarea
        class="form-control"
        id="instructions"
        name="instructions"
        rows="5"
      >
{{ recipe_data.recipeInstructions }}</textarea
      >
    </div>
    <div class="form-group">
      <label for="notes">Notes:</label>
      <textarea class="form-control" id="notes" name="notes" rows="3">
      {{ recipe_data.notes }}</textarea
      >
    </div>
    <div class="form-group">
      <label for="image">Image:</label>
      <input type="file" class="form-control-file" id="image" name="image" />
    </div>
    <div class="form-group">
      <label for="source">Source:</label>
      <input
        type="url"
        class="form-control"
        id="source"
        name="source"
        value="{{ recipe_data.source }}"
      />
    </div>
    <input type="hidden" name="recipe_data" value="{{ recipe_data }}" />

    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="/recipes" class="btn btn-secondary">Back to all recipes</a>
  </form>

  <!-- Form to process the recipe data with the LLM using HTMX -->
  <button
    class="btn btn-warning mt-3"
    hx-post="/recipes/process-recipe"
    hx-include="#create-recipe-form"
    hx-target="body"
    hx-swap="outerHTML"
  >
    Process Recipe Data
  </button>
</div>

{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %} {% endblock %}

app/templates/recipe_detail.html
{% extends 'layout.html' %} {% block content %} {% include
'partials/nav_bar.html' with context %}
<div class="container mt-5 pt-4">
  <div class="card mb-4">
    <div class="row no-gutters">
      <div class="col-md-4">
        {% if recipe.imageUrl %}
        <img
          src="{{ recipe.imageUrl }}"
          class="card-img"
          alt="{{ recipe.name }}"
        />
        {% else %}
        <img
          src="{{ url_for('static', filename='images/default-recipe-image.jpg') }}"
          class="card-img"
          alt="Default Image"
        />
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h1 class="card-title text-uppercase">{{ recipe.name }}</h1>
          <p class="card-text">
            <strong>Description:</strong> {{ recipe.description }}
          </p>
          <p class="card-text">
            <strong>Category:</strong> {{ recipe.recipe_cuisine }}
          </p>
          <p class="card-text"><strong>Tags:</strong> {{ recipe.keywords }}</p>
          <p class="card-text">
            <strong>Servings:</strong> {{ recipe.recipe_yield }}
          </p>
          <p class="card-text">
            <strong>Prep Time:</strong> {{ recipe.prep_time }} minutes
          </p>
          <p class="card-text">
            <strong>Cook Time:</strong> {{ recipe.cook_time }} minutes
          </p>
          <p class="card-text">
            <strong>Source:</strong>
            <a href="{{ recipe.source }}" target="_blank"
              >{{ recipe.source }}</a
            >
          </p>
          <h2 class="card-title">Ingredients</h2>
          <p class="card-text">{{recipe.recipe_ingredients_raw}}</p>
          <h2 class="card-title">Method</h2>
          <p class="card-text">{{recipe.recipe_instructions_raw}}</p>
          <h2 class="card-title">Notes</h2>
          <p class="card-text">{{ recipe.notes }}</p>
          <a
            class="btn btn-primary"
            href="{{ url_for('recipes.edit_recipe', recipe_id=recipe.id) }}"
            role="button"
            >Edit recipe</a
          >
          <form
            action="{{ url_for('recipes.delete_recipe', recipe_id=recipe.id) }}"
            method="POST"
            class="d-inline"
          >
            <button
              type="submit"
              onclick="return confirm('Are you sure you want to delete this recipe?');"
              class="btn btn-danger"
            >
              Delete
            </button>
          </form>
          <a
            class="btn btn-secondary"
            href="{{ url_for('recipes.recipes_list') }}"
            role="button"
            >Back to all recipes</a
          >
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/recipe_edit.html
<!-- templates/recipe_edit.html -->

{% extends 'layout.html' %} {% block content %} {% include
'partials/nav_bar.html' with context %}

<div class="container mt-5 pt-4">
  <h1>Edit Recipe</h1>

  <form
    action="{{ url_for('recipes.edit_recipe', recipe_id=recipe.id) }}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-group">
      <label for="name">Name:</label>
      <input
        type="text"
        class="form-control"
        id="name"
        name="name"
        value="{{ recipe.name }}"
        required
      />
    </div>
    <div class="form-group">
      <label for="description">Description:</label>
      <textarea
        class="form-control"
        id="description"
        name="description"
        rows="3"
      >
{{ recipe.description }}</textarea
      >
    </div>
    <div class="form-group">
      <label for="category">Category:</label>
      <input
        type="text"
        class="form-control"
        id="category"
        name="category"
        value="{{ recipe.category }}"
      />
    </div>
    <div class="form-group">
      <label for="tag">Tag:</label>
      <input
        type="text"
        class="form-control"
        id="tag"
        name="tag"
        value="{{ recipe.tag }}"
      />
    </div>
    <div class="form-group">
      <label for="servings">Servings:</label>
      <input
        type="number"
        class="form-control"
        id="servings"
        name="servings"
        value="{{ recipe.servings }}"
      />
    </div>
    <div class="form-group">
      <label for="preptime">Prep Time (minutes):</label>
      <input
        type="number"
        class="form-control"
        id="preptime"
        name="preptime"
        value="{{ recipe.prep_time }}"
      />
    </div>
    <div class="form-group">
      <label for="cooktime">Cook Time (minutes):</label>
      <input
        type="number"
        class="form-control"
        id="cooktime"
        name="cooktime"
        value="{{ recipe.cook_time }}"
      />
    </div>
    <div class="form-group">
      <label for="ingredients">Ingredients (Markdown supported):</label>
      <textarea
        class="form-control"
        id="ingredients"
        name="ingredients"
        rows="5"
      >
{{ recipe.ingredients }}</textarea
      >
    </div>
    <div class="form-group">
      <label for="method">Method (Markdown supported):</label>
      <textarea class="form-control" id="method" name="method" rows="5">
          {{ recipe.method }}</textarea
      >
    </div>
    <div class="form-group">
      <label for="notes">Notes:</label>
      <textarea class="form-control" id="notes" name="notes" rows="3">
          {{ recipe.notes }}</textarea
      >
    </div>
    <div class="form-group">
      <label for="source">Source:</label>
      <input
        type="url"
        class="form-control"
        id="source"
        name="source"
        value="{{ recipe.source }}"
      />
    </div>
    <div class="form-group">
      <label for="image">Image:</label>
      <input type="file" class="form-control-file" id="image" name="image" />
    </div>
    <button type="submit" class="btn btn-primary">Save Changes</button>
    <a
      href="{{ url_for('recipes.recipe_detail', recipe_id=recipe.id) }}"
      class="btn btn-secondary"
      >Back to Recipe</a
    >
    <a href="{{ url_for('recipes.recipes_list') }}" class="btn btn-secondary"
      >Back to all recipes</a
    >
  </form>
</div>
​⬤ {% endblock %}

app/templates/recipes.html
<!-- templates/sign-up-form.html -->

{% extends 'layout.html' %} {% block content %} {% include
'partials/nav_bar.html' with context %}
<div class="container mt-5 pt-4">
  <div class="row">
    {% if recipes %} {% for recipe in recipes %}
    <div class="col-md-12 mb-4">
      <div class="card">
        <div class="row no-gutters">
          <div class="col-md-2">
            {% if recipe.imageUrl %}
            <img
              src="{{ recipe.imageUrl }}"
              class="card-img"
              alt="{{ recipe.name }}"
            />
            {% else %}
            <img
              src="{{ url_for('static', filename='images/default-recipe-image.jpg') }}"
              class="card-img"
              alt="Default Image"
            />
            {% endif %}
          </div>
          <div class="col-md-10">
            <div class="card-body">
              <h5 class="card-title text-uppercase">{{ recipe.name }}</h5>
              <p class="card-text">{{ recipe.description }}</p>
              <p class="card-text">
                <small class="text-muted">⏱ {{ recipe.cook_time }} min</small>
              </p>
              <a
                href="{{ url_for('recipes.recipe_detail', recipe_id=recipe.id) }}"
                class="btn btn-link p-0"
                >Read More</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %} {% endif %}
  </div>
  <a class="btn btn-primary mt-4" href="{{ url_for('recipes.create_recipe') }}"
    >Create a recipe</a
  >
</div>

{% endblock %}

app/templates/sign-up-form.html
<!-- templates/sign-up-form.html -->

{% extends 'layout.html' %} {% block content %}

<div class="container-fluid h-100">
  <div class="row h-100">
    {% include 'partials/home_side_panel.html' %}
    <div
      class="col-md-9 d-flex flex-column align-items-center justify-content-center"
    >
      <div class="w-50">
        <form action="" method="POST" class="needs-validation" novalidate>
          <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input
              name="username"
              type="text"
              class="form-control"
              id="username"
              placeholder="username"
              required
            />
            <div class="invalid-feedback">Please enter a username.</div>
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input
              name="password"
              type="password"
              class="form-control"
              id="password"
              placeholder="password"
              required
            />
            <div class="invalid-feedback">Please enter a password.</div>
          </div>
          <button type="submit" class="btn btn-primary w-100">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}